### ISSUE TITLE
**NUTRITION INFO**

### ISSUE THREAD

**Issue by techx-guy** [julioPlaceres/TastyBytes#60]
- calories (done)
- fat (done)
- sugar (done)
- protein (done)
- carbs (can't find it)
- is vegan/veg/GF (working on it)
- Prep Time (done) 
- Cook Time (done)
- Source Name/URL (probably needed since it is extracted from somewhere else, let's not get sued lol) (working on it)
- Health Score / Popularity (probably at the bottom to rate the dish) (working on it)

**Comment by julioPlaceres** [comment]
This is all set.
